import { useEffect, useRef, useState, type ReactNode } from 'react';
import { api, apiWrite, logout } from '../../client.ts';
import { AppViewport, Screen } from './AppShell.tsx';
import { BottomNav } from './BottomNav.tsx';
import { Icon } from './Icon.tsx';
import { AppHeader, BackHeader, Chip, EmptyState, ErrorState, FriendRow, NotificationRow, PovodButton, PovodSheet, SearchField, SettingsRow, StatusChip } from './PovodUI.tsx';
import type { Route } from '../port/contracts.ts';
import './v2-runtime.css';
import {share as shareInMax} from '../../bridge.ts';

export type PreferencePage = 'interests'|'city'|'budget'|'time'|'radius'|'notification-preferences'|'linked-services';
type Preferences = {city:string;interests:string[];budgetRub:number|null;radiusKm:number;notificationsEnabled:boolean;preferredTime:'ANY'|'MORNING'|'DAY'|'EVENING'|'NIGHT'};
type Actor = {id:string;displayName:string};
type Friend = {id:string;name:string;state:string;direction:string};
function uniqueFriends(items:Friend[]):Friend[]{
 const byActor=new Map<string,Friend>();
 for(const friend of items){const old=byActor.get(friend.id);if(!old||friend.state==='ACCEPTED'&&old.state!=='ACCEPTED')byActor.set(friend.id,friend)}
 return [...byActor.values()];
}
type Notice = {id:string;kind:string;title:string;planId:string|null;inviteRef:string|null;read:boolean;createdAt:string;actorName:string|null;planTitle:string|null;eventTitle:string|null};
type Rsvp = 'YES'|'MAYBE'|'NO';
type Plan = {planId:string;title:string;stateVersion:number;phase:string;capabilities:{canManage:boolean};rule:{kind:'ALL'|'MIN';n?:number};decisionDeadline:string;options:{optionId:string;source?:{ref?:{provider_id:string;event_id:string;occurrence_id:string}};terms:{title:string;startsAt:string|null;endsAt:string|null;place:string|null}}[];slots:{slotId:string;label:string;required:boolean;actorId:string|null;state:string}[]};
type Change = {from:string|null;to:string|null};
type Presentation = {version:number;reconfirmVersion:number;title:string;meetingTime:string|null;meetingPoint:string|null;note:string|null;participantLimit:number|null;maxParticipants:number;phase:string;organizerId:string;organizerName:string;changedFields:Record<string,Change>};
const interests = ['Музыка','Стендап','Выставки','Театр','Кино','Фестивали','Лекции','Спорт','Гастрономия','Искусство','Вечеринки','Для детей'];
const timeOptions = [{id:'ANY',label:'Любое'},{id:'MORNING',label:'Утром'},{id:'DAY',label:'Днём'},{id:'EVENING',label:'Вечером'},{id:'NIGHT',label:'Ночью'}] as const;
const cityOptions = ['Москва','Санкт-Петербург','Казань','Екатеринбург','Новосибирск'];
const rsvpAction:Record<Rsvp,string>={YES:'Пойду',MAYBE:'Подумаю',NO:'Не смогу'};
const rsvpState:Record<Rsvp,string>={YES:'Иду',MAYBE:'Думает',NO:'Не идёт'};
const date = (value:string|null) => value ? new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(value)) : 'Время уточняется';
// P0 city is Moscow. Interpret the plan meeting input in Moscow, independent of browser timezone.
const toLocal = (value:string|null) => value ? new Date(Date.parse(value)+3*3600000).toISOString().slice(0,16) : '';
const backToIso = (value:string) => value ? new Date(value+':00+03:00').toISOString() : null;
async function shareOrCopy(title:string,url:string,onDone:(copied:boolean)=>void,onError:()=>void){
 const result=await shareInMax(title,url);
 if(result==='INVOKED')onDone(false);else onError();
}

function Frame({title,active='profile',onBack,onNavigate,children,headerAction}: {title:string;active?:string;onBack?:()=>void;onNavigate:(id:string)=>void;children:ReactNode;headerAction?:ReactNode}) {
 return <AppViewport><Screen className={`v2-page${onBack?' v2-nested-page':''}`}>{onBack?<BackHeader title={title} onBack={onBack} action={headerAction}/>:<header className="v2-page-heading"><h1>{title}</h1>{headerAction}</header>}<div className="v2-content">{children}</div></Screen>{!onBack&&<BottomNav active={active} onSelect={onNavigate}/>}</AppViewport>;
}
function usePreferences(){
 const [value,setValue]=useState<Preferences|null>(null),[error,setError]=useState(''),[tick,setTick]=useState(0);
 useEffect(()=>{let live=true;api<Preferences>('/api/v1/me/preferences').then(x=>{if(live){setValue(x);setError('')}}).catch(()=>{if(live)setError('Не удалось загрузить предпочтения')});return()=>{live=false}},[tick]);
 const save=async(next:Preferences)=>{try{const saved=await apiWrite<Preferences>('PUT','/api/v1/me/preferences',next);setValue(saved);setError('');return true}catch{setError('Не удалось сохранить. Попробуйте ещё раз.');return false}};
 return {value,error,retry:()=>setTick(x=>x+1),save};
}
export function ProfileRuntime({onNavigate,onSaved,onSettings,onNotifications,onPreference}:{onNavigate:(id:string)=>void;onSaved:()=>void;onSettings:()=>void;onNotifications:()=>void;onPreference:(page:PreferencePage)=>void}){
 const {value,error,retry}=usePreferences();const [actor,setActor]=useState<Actor|null>(null);
 useEffect(()=>{void api<{actor:Actor}>('/api/v1/session').then(x=>setActor(x.actor)).catch(()=>{})},[]);
 return <Frame title="Профиль" onNavigate={onNavigate} headerAction={<button className="v2-heading-icon" type="button" aria-label="Настройки" onClick={onSettings}><Icon name="settings"/></button>}>
  {error&&<ErrorState message={error} onRetry={retry}/>}
  {!value||!actor?<p role="status">Загружаем профиль…</p>:<>
   <div className="v2-identity"><span className="v2-avatar v2-avatar-large">{actor.displayName.slice(0,1)}</span><span><strong>{actor.displayName}</strong><small>Профиль в Поводе</small></span></div>
   <SettingsRow icon="pin" label="Город" value={value.city} onClick={()=>onPreference('city')}/>
   <section className="v2-section"><div className="v2-section-head"><h2>Интересы</h2><button type="button" onClick={()=>onPreference('interests')}>Изменить</button></div><div className="v2-chip-row">{value.interests.length?value.interests.map(x=><Chip key={x} selected onClick={()=>onPreference('interests')}>{x}</Chip>):<p className="v2-muted">Выберите, что вам интересно</p>}</div></section>
   <section className="v2-section" aria-label="Предпочтения">
    <SettingsRow icon="wallet" label="Бюджет на событие" value={value.budgetRub===null?'Любой':`До ${value.budgetRub.toLocaleString('ru-RU')} ₽`} onClick={()=>onPreference('budget')}/>
    <SettingsRow icon="clock" label="Предпочтительное время" value={timeOptions.find(x=>x.id===value.preferredTime)?.label} onClick={()=>onPreference('time')}/>
    <SettingsRow icon="pin" label="Радиус поиска" value={`${value.radiusKm} км`} onClick={()=>onPreference('radius')}/>
    <SettingsRow icon="bell" label="Уведомления" value={value.notificationsEnabled?'Включены':'Выключены'} onClick={()=>onPreference('notification-preferences')}/>
   </section>
   <section className="v2-section"><h2>Мой Повод</h2><SettingsRow icon="bookmark" label="Сохранённое" onClick={onSaved}/><SettingsRow icon="people" label="Друзья" onClick={()=>onNavigate('friends')}/><SettingsRow icon="calendar" label="Мои планы" onClick={()=>onNavigate('plan')}/></section>
   <SettingsRow icon="user" label="Связанные сервисы" value="MAX" onClick={()=>onPreference('linked-services')}/>
   <SettingsRow icon="settings" label="Настройки" onClick={onSettings}/>
   <button type="button" className="v2-notice-link" onClick={onNotifications}>Открыть уведомления</button>
  </>}
 </Frame>;
}

export function PreferenceRuntime({page,onNavigate,onBack,onOpenCity}:{page:PreferencePage;onNavigate:(id:string)=>void;onBack:()=>void;onOpenCity:()=>void}){
 const {value,error,retry,save}=usePreferences();const [draft,setDraft]=useState<Preferences|null>(null),[busy,setBusy]=useState(false);
 const [locationState,setLocationState]=useState('Проверяем доступ к местоположению…');
 useEffect(()=>{if(value)setDraft(value)},[value]);
 useEffect(()=>{if(page!=='radius')return;let live=true;if(!navigator.geolocation){setLocationState('Геолокация недоступна в этом браузере.');return}
  if(!navigator.permissions?.query){setLocationState('Состояние разрешения неизвестно.');return}
  void navigator.permissions.query({name:'geolocation'}).then(permission=>{const update=()=>{if(live)setLocationState(permission.state==='granted'?'Доступ к местоположению разрешён.':permission.state==='denied'?'Доступ к местоположению запрещён в браузере.':'Браузер спросит разрешение при поиске рядом.')};update();permission.addEventListener('change',update)}).catch(()=>{if(live)setLocationState('Состояние разрешения неизвестно.')});return()=>{live=false}},[page]);
 const title:Record<PreferencePage,string>={interests:'Интересы',city:'Выбор города',budget:'Бюджет',time:'Предпочтительное время',radius:'Где искать события','notification-preferences':'Уведомления','linked-services':'Связанные сервисы'};
 const apply=async()=>{if(!draft)return;setBusy(true);if(await save(draft))onBack();setBusy(false)};
 return <Frame title={title[page]} onBack={onBack} onNavigate={onNavigate}>
  {error&&<ErrorState message={error} onRetry={retry}/>}
  {!draft?<p role="status">Загружаем…</p>:<>
   {page==='interests'&&<><h2 className="v2-editor-title">Выберите, что вам интересно</h2><p className="v2-muted">Мы будем показывать более точные рекомендации.</p><div className="v2-chip-row">{interests.map(x=><Chip key={x} selected={draft.interests.includes(x)} onClick={()=>setDraft({...draft,interests:draft.interests.includes(x)?draft.interests.filter(y=>y!==x):[...draft.interests,x]})}>{x}</Chip>)}</div></>}
   {page==='city'&&<><input className="v2-input" type="search" aria-label="Поиск города" placeholder="Поиск города" onChange={e=>{const list=document.querySelectorAll<HTMLElement>('[data-city]');list.forEach(node=>{node.hidden=!node.dataset.city?.toLowerCase().includes(e.target.value.toLowerCase())})}}/>{draft.city!=='Москва'&&<div className="v2-city-current"><Icon name="pin"/><span>Текущий город<strong>{draft.city}</strong></span></div>}<h2 className="v2-editor-title">Доступно сейчас</h2><button type="button" className="v2-city-row" data-city="Москва" onClick={()=>setDraft({...draft,city:'Москва'})}><span>Москва</span><StatusChip tone="red">События доступны</StatusChip></button><h2 className="v2-editor-title">Скоро в Поводе</h2>{cityOptions.slice(1).map(x=><button type="button" className="v2-city-row" data-city={x} key={x} onClick={()=>setDraft({...draft,city:x})}><span>{x}</span><StatusChip>Скоро</StatusChip></button>)}{draft.city!=='Москва'&&<p className="v2-coverage">В этом городе пока нет подтверждённых событий. Можно вернуться к Москве в любое время.</p>}</>}
   {page==='budget'&&<><p className="v2-muted">Ваш бюджет сохранится в профиле. Для точной выдачи установите фильтр цены в Поиске.</p><div className="v2-chip-row">{[null,...Array.from(new Set([1000,1500,2000,3000,5000,...(draft.budgetRub===null?[]:[draft.budgetRub])])).sort((a,b)=>a-b)].map(n=><Chip key={n??'any'} selected={draft.budgetRub===n} onClick={()=>setDraft({...draft,budgetRub:n})}>{n===null?'Любой':`До ${n.toLocaleString('ru-RU')} ₽`}</Chip>)}</div></>}
   {page==='time'&&<><p className="v2-muted">Сохраните удобное время в профиле. Текущая выдача поиска пока не использует это предпочтение.</p><div className="v2-chip-row">{timeOptions.map(x=><Chip key={x.id} selected={draft.preferredTime===x.id} onClick={()=>setDraft({...draft,preferredTime:x.id})}>{x.label}</Chip>)}</div></>}
   {page==='radius'&&<><p className="v2-muted">Расстояние используется для событий с известными координатами, если разрешена геолокация.</p><div className="v2-location-state"><Icon name="pin"/><span><strong>Местоположение</strong><small>{locationState}</small></span></div>{navigator.geolocation&&<PovodButton variant="secondary" onClick={()=>navigator.geolocation.getCurrentPosition(()=>setLocationState('Местоположение доступно. Поиск рядом использует радиус ниже.'),()=>setLocationState('Местоположение недоступно. Проверьте разрешение в браузере или выберите город.'),{timeout:5000,maximumAge:300000})}>Проверить местоположение</PovodButton>}<PovodButton variant="quiet" onClick={onOpenCity}>Выбрать город вручную</PovodButton><div className="v2-radius-value">{draft.radiusKm} км</div><input className="v2-range" aria-label="Радиус поиска в километрах" type="range" min="1" max="50" step="1" value={draft.radiusKm} onChange={e=>setDraft({...draft,radiusKm:Number(e.target.value)})}/><div className="v2-range-labels"><span>1 км</span><span>25 км</span><span>50 км</span></div></>}
   {page==='notification-preferences'&&<SettingsRow icon="bell" label="Уведомления о планах и приглашениях" value={draft.notificationsEnabled?'Включены':'Выключены'} onClick={()=>setDraft({...draft,notificationsEnabled:!draft.notificationsEnabled})}/>}
   {page==='linked-services'&&<><div className="v2-card"><strong>MAX</strong><p className="v2-muted">Ваш аккаунт Повода связан с входом через MAX.</p></div><p className="v2-muted">Другие сервисы пока недоступны.</p></>}
   {page!=='linked-services'&&<PovodButton onClick={()=>void apply()} disabled={busy}>Сохранить</PovodButton>}
  </>}
 </Frame>;
}

export function SettingsRuntime({onNavigate,onBack,onNotifications}:{onNavigate:(id:string)=>void;onBack:()=>void;onNotifications:()=>void}){
 const [section,setSection]=useState<'main'|'account'|'privacy'|'help'|'about'>('main');
 const [actor,setActor]=useState<Actor|null>(null),[signedOut,setSignedOut]=useState(false),[logoutError,setLogoutError]=useState('');
 useEffect(()=>{void api<{actor:Actor}>('/api/v1/session').then(x=>setActor(x.actor)).catch(()=>{})},[]);
 if(signedOut)return <AppViewport><Screen className="v2-page"><div className="v2-content"><EmptyState icon="user" title="Вы вышли из Повода" description="Чтобы продолжить, снова откройте приложение из MAX."/></div></Screen></AppViewport>;
 return <Frame title={section==='main'?'Настройки':({account:'Аккаунт',privacy:'Приватность',help:'Помощь',about:'О Поводе'} as const)[section]} onBack={section==='main'?onBack:()=>setSection('main')} onNavigate={onNavigate}>
  {logoutError&&<ErrorState message={logoutError}/>}
  {section==='main'?<><SettingsRow icon="user" label="Аккаунт" onClick={()=>setSection('account')}/><SettingsRow icon="user" label="Приватность" onClick={()=>setSection('privacy')}/><SettingsRow icon="bell" label="Уведомления" onClick={onNotifications}/><SettingsRow icon="search" label="Помощь" onClick={()=>setSection('help')}/><SettingsRow icon="bookmark" label="О Поводе" onClick={()=>setSection('about')}/><PovodButton variant="outline" onClick={()=>void logout().then(()=>setSignedOut(true)).catch(()=>setLogoutError('Не удалось завершить сессию. Повторите попытку.'))}>Выйти</PovodButton></>:
   <div className="v2-card v2-settings-information">{section==='account'?<><strong>{actor?.displayName??'Профиль Повода'}</strong><p>Вход в Повод выполняется через MAX. Имя и параметры учётной записи меняются в MAX.</p><p>После выхода откройте Повод снова из MAX, чтобы продолжить.</p></>:section==='privacy'?<><strong>Друзья и планы</strong><p>Приглашения и запросы связывают людей внутри Повода. Детали плана доступны его участникам и организатору.</p><p>Вы сами выбираете, кому отправить ссылку на приглашение. Геолокация используется для поиска рядом только при разрешении браузера.</p></>:section==='help'?<><strong>Поиск и события</strong><p>Если события не появились, проверьте город и фильтры. Подтверждённый каталог сейчас доступен для Москвы.</p><strong>Планы и приглашения</strong><p>Ответьте на приглашение в плане. Если условия встречи изменились, Повод попросит ответить ещё раз.</p><strong>Доступ</strong><p>При ошибке соединения повторите действие. Если сессия закончилась, откройте Повод снова из MAX.</p></>:<><strong>Повод</strong><p>Ищите события, сохраняйте интересное и собирайте планы с друзьями.</p><p>Дата, место, цена и сведения об источнике показываются по доступным данным события. Условия совместной встречи задаёт организатор плана.</p></>}</div>}
 </Frame>;
}

export function FriendsRuntime({onNavigate,onBack,inviteToken}:{onNavigate:(id:string)=>void;onBack:()=>void;inviteToken?:string|null}){
 const [friends,setFriends]=useState<Friend[]|null>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[sheet,setSheet]=useState(false),[link,setLink]=useState(''),[status,setStatus]=useState(''),[tick,setTick]=useState(0);
 const [linkStatus,setLinkStatus]=useState<{name:string;state:string}|null>(null);
 useEffect(()=>{let live=true;api<{items:Friend[]}>('/api/v1/me/friends').then(x=>{if(live){setFriends(uniqueFriends(x.items));setError('')}}).catch(()=>{if(live)setError('Не удалось загрузить друзей')});return()=>{live=false}},[tick]);
 useEffect(()=>{if(!inviteToken)return;let live=true;void api<{name:string;state:string}>(`/api/v1/friend-links/${inviteToken}/status`).then(x=>{if(live)setLinkStatus(x)}).catch(()=>{if(live)setError('Приглашение недоступно')});return()=>{live=false}},[inviteToken,tick]);
 const invite=async()=>{setSheet(true);if(link)return;try{const x=await apiWrite<{token:string}>('POST','/api/v1/me/friend-links',{});const result=await api<{url:string}>('/api/v1/launch/link',{kind:'FRIEND',friendRef:x.token});setLink(result.url)}catch{setError('Не удалось подготовить приглашение')}};
 const request=async()=>{if(!inviteToken||linkStatus?.state!=='AVAILABLE')return;try{const result=await apiWrite<{requested:boolean;state:string}>('POST',`/api/v1/friend-links/${inviteToken}/request`,{});setStatus(result.requested?'Запрос отправлен. Друг увидит его в Поводе.':'Запрос уже ожидает ответа.');setLinkStatus({...linkStatus,state:'PENDING'});setTick(x=>x+1)}catch{setError('Не удалось отправить запрос. Ссылка могла устареть.')}};
 const filtered=friends?.filter(f=>f.name.toLowerCase().includes(search.toLowerCase()));
 return <Frame title="Друзья" active="friends" onNavigate={onNavigate} onBack={inviteToken?onBack:undefined} headerAction={<button type="button" className="v2-heading-icon" aria-label="Пригласить друга" onClick={()=>void invite()}><Icon name="plus"/></button>}>
  {inviteToken&&linkStatus&&<div className="v2-card v2-invite-banner"><strong>{linkStatus.name}</strong><p className="v2-muted">{linkStatus.state==='FRIEND'?'Вы уже друзья в Поводе.':linkStatus.state==='PENDING'?'Запрос в друзья ожидает ответа.':linkStatus.state==='REJECTED'?'Запрос в друзья был отклонён.':linkStatus.state==='SELF'?'Это ваша ссылка для приглашения.':'Отправьте запрос, чтобы добавиться в Поводе.'}</p>{linkStatus.state==='AVAILABLE'&&<PovodButton onClick={()=>void request()}>Отправить запрос</PovodButton>}</div>}
  <SearchField value={search} onChange={setSearch} placeholder="Найти среди друзей"/>
  {error&&<ErrorState message={error} onRetry={()=>setTick(x=>x+1)}/>}
  {status&&<p role="status" className="v2-feedback">{status}</p>}
  {!friends&&!error?<p role="status">Загружаем друзей…</p>:filtered?.length?<ul className="v2-list">{filtered.map(f=><FriendRow key={f.id} name={f.name} subtitle={f.state==='ACCEPTED'?'Друг в Поводе':f.direction==='INCOMING'?'Ждёт вашего ответа':'Приглашение отправлено'} action={f.state==='PENDING'&&f.direction==='INCOMING'?<span className="v2-friend-actions"><PovodButton variant="outline" onClick={()=>void apiWrite('POST',`/api/v1/me/friends/${f.id}/accept`,{}).then(()=>setTick(x=>x+1)).catch(()=>setError('Не удалось принять запрос'))}>Принять</PovodButton><PovodButton variant="quiet" onClick={()=>void apiWrite('POST',`/api/v1/me/friends/${f.id}/reject`,{}).then(()=>setTick(x=>x+1)).catch(()=>setError('Не удалось отклонить запрос'))}>Отклонить</PovodButton></span>:<StatusChip tone={f.state==='ACCEPTED'?'green':'violet'}>{f.state==='ACCEPTED'?'Друг':'Ожидание'}</StatusChip>}/>)}</ul>:<EmptyState icon="people" title={search?'Друзья не найдены':'Пока друзей нет'} description={search?'Попробуйте другое имя.':'Пригласите человека через MAX или отправьте ему ссылку.'} action={!search?<PovodButton onClick={()=>void invite()}>Пригласить друга</PovodButton>:undefined}/>}
  <PovodSheet open={sheet} onClose={()=>setSheet(false)} title="Пригласить друга"><p className="v2-muted">Поделитесь ссылкой в MAX. Человек сможет отправить вам запрос в Поводе.</p><div className="v2-actions">{link&&<><PovodButton icon="max" onClick={()=>void shareOrCopy('Добавиться в друзья в Поводе',link,()=>{setSheet(false);setStatus('Открыт выбор получателя в MAX.')},()=>setError('MAX недоступен. Скопируйте ссылку.'))}>Поделиться в MAX</PovodButton><PovodButton variant="secondary" icon="copy" onClick={()=>void navigator.clipboard.writeText(link).then(()=>{setSheet(false);setStatus('Ссылка скопирована')}).catch(()=>setError('Не удалось скопировать ссылку'))}>Скопировать ссылку</PovodButton></>}</div></PovodSheet>
 </Frame>;
}

export function NotificationsRuntime({onNavigate,onBack,onOpenPlan,onOpenInvite}:{onNavigate:(id:string)=>void;onBack:()=>void;onOpenPlan:(id:string)=>void;onOpenInvite:(ref:string)=>void}){
 const [items,setItems]=useState<Notice[]|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;api<{items:Notice[]}>('/api/v1/me/notifications').then(x=>{if(live)setItems(x.items.filter(n=>n.kind!=='PLAN_CHAT'))}).catch(()=>{if(live)setError('Не удалось загрузить уведомления')});return()=>{live=false}},[]);
 const open=async(n:Notice)=>{try{await apiWrite('POST',`/api/v1/me/notifications/${n.id}/read`,{});setItems(current=>current?.map(x=>x.id===n.id?{...x,read:true}:x)??null);window.dispatchEvent(new Event('povod:notifications-read'));if(n.inviteRef)onOpenInvite(n.inviteRef);else if(n.planId)onOpenPlan(n.planId);else if(n.kind==='FRIEND_REQUEST')onNavigate('friends')}catch{setError('Не удалось открыть уведомление')}};
 return <Frame title="Уведомления" onNavigate={onNavigate} onBack={onBack}>
  {error&&<ErrorState message={error}/>}
  {!items&&!error?<p role="status">Загружаем уведомления…</p>:items?.length?<ul className="v2-list">{items.map(n=><NotificationRow key={n.id} action={n.title} actorName={n.actorName} planTitle={n.planTitle} eventTitle={n.eventTitle} createdAt={n.createdAt} unread={!n.read} icon={n.kind==='FRIEND_REQUEST'?'people':n.kind==='REMINDER'?'bell':'calendar'} onOpen={()=>void open(n)}/>)}</ul>:<EmptyState icon="bell" title="Пока уведомлений нет" description="Приглашения и изменения планов появятся здесь."/>}
 </Frame>;
}

function EventSummary({plan,people=[]}:{plan:Plan;people?:string[]}){
 const event=plan.options[0]?.terms;
 return <div className="v2-event-summary"><span className="v2-event-art"><Icon name="calendar"/></span><span><strong>{event?.title??'Событие'}</strong><small>{date(event?.startsAt??null)}</small><small>{event?.place??'Место уточняется'}</small>{people.length>0&&<span className="v2-share-participants"><span className="v2-plan-avatars" aria-label={`Люди в плане: ${people.join(', ')}`}>{people.slice(0,3).map((name,index)=><span className="v2-avatar" key={`${name}-${index}`} title={name}>{name.slice(0,1)}</span>)}</span><small>Люди в плане: {people.length}</small></span>}</span></div>;
}
function PlanCard({plan,presentation,rsvp,needsReconfirmation,participantNames,onOpen}:{plan:Plan;presentation:Presentation|undefined;rsvp:Rsvp|undefined;needsReconfirmation:boolean;participantNames:string[];onOpen:()=>void}){
 const start=plan.options[0]?.terms.startsAt;
 const day=start?new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit'}).format(new Date(start)):'—';
 const month=start?new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',month:'short'}).format(new Date(start)):'Дата';
 return <button type="button" className="v2-plan-card" onClick={onOpen}><span className="v2-plan-card-top"><span className="v2-plan-date" aria-hidden="true"><strong>{day}</strong><small>{month}</small></span><span className="v2-plan-card-info"><strong className="v2-plan-title">{presentation?.title??plan.title}</strong><span className="v2-plan-event-name">{plan.options[0]?.terms.title??'Событие'}</span><small>{date(start??null)} · {plan.options[0]?.terms.place??'Место уточняется'}</small></span></span><span className="v2-plan-card-bottom"><span className="v2-plan-card-social">{participantNames.length>0&&<span className="v2-plan-avatars" aria-label={`Участники: ${participantNames.join(', ')}`}>{participantNames.slice(0,3).map((name,index)=><span className="v2-avatar" key={`${name}-${index}`} title={name}>{name.slice(0,1)}</span>)}</span>}<span>{presentation?.organizerId===undefined?(plan.capabilities.canManage?'Вы организатор':'План с друзьями'):plan.capabilities.canManage?'Вы организатор':`Организатор: ${presentation.organizerName}`}{presentation?.meetingTime?` · Встреча ${date(presentation.meetingTime)}`:''}</span></span><StatusChip tone={plan.phase==='CANCELLED'?'red':needsReconfirmation?'red':rsvp==='YES'?'green':'violet'}>{plan.phase==='CANCELLED'?'Отменён':needsReconfirmation?'Ответить снова':rsvp?rsvpState[rsvp]:'План'}</StatusChip><Icon name="chevronRight"/></span></button>;
}
const changeLabels:Record<string,string>={title:'Название плана',meetingTime:'Время встречи',meetingPoint:'Точка встречи',note:'Заметка',participantLimit:'Лимит участников'};
const changedValue=(key:string,value:string|null)=>value===null?'Не задано':key==='meetingTime'?date(value):value;
function CalendarAction({plan,presentation}:{plan:Plan;presentation:Presentation}){
 const download=()=>{
  const event=plan.options[0]?.terms;if(!event?.startsAt)return;
  const stamp=(value:string)=>new Date(value).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
  const escape=(value:string)=>value.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
  const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//POVOD//Plan//RU','BEGIN:VEVENT',`UID:${plan.planId}@povod`,`DTSTAMP:${stamp(new Date().toISOString())}`,`DTSTART:${stamp(presentation.meetingTime??event.startsAt)}`,`SUMMARY:${escape(presentation.title)}`,`LOCATION:${escape(presentation.meetingPoint??event.place??'')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');
  const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='povod-plan.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 };
 return <PovodButton variant="secondary" icon="calendar" onClick={download} disabled={!plan.options[0]?.terms.startsAt}>Добавить в календарь</PovodButton>;
}
export function PlansRuntime({onNavigate,selected,onSelect,onOpenEvent}:{onNavigate:(id:string)=>void;selected:string|null;onSelect:(id:string|null)=>void;onOpenEvent?:(route:Extract<Route,{kind:'EVENT'}>)=>void}){
 const meetingInput=useRef<HTMLInputElement>(null);
 const [plans,setPlans]=useState<Plan[]|null>(null),[actor,setActor]=useState<Actor|null>(null),[friends,setFriends]=useState<Friend[]>([]),[presentations,setPresentations]=useState<Record<string,Presentation>>({}),[rsvps,setRsvps]=useState<Record<string,{actorId:string;state:Rsvp;needsReconfirmation?:boolean}[]>>({}),[joins,setJoins]=useState<{actorId:string;name:string}[]>([]),[inviteStatuses,setInviteStatuses]=useState<Record<string,string>>({});
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[tick,setTick]=useState(0),[sheet,setSheet]=useState<'none'|'rsvp'|'invite'|'edit'|'cancel'|'share'>('none'),[edit,setEdit]=useState<Presentation|null>(null),[shareUrl,setShareUrl]=useState('');
 const [period,setPeriod]=useState<'upcoming'|'past'>('upcoming');
 useEffect(()=>{let live=true;(async()=>{try{
  const [list,session,fs]=await Promise.all([api<{items:{id:string}[]}>('/api/v1/plans?limit=50'),api<{actor:Actor}>('/api/v1/session'),api<{items:Friend[]}>('/api/v1/me/friends')]);
  const ids=[...new Set([...list.items.map(p=>p.id),...(selected?[selected]:[])])];
  const detail=await Promise.all(ids.map(id=>api<Plan>(`/api/v1/plans/${id}`)));
  if(!live)return;setPlans(detail);setActor(session.actor);setFriends(uniqueFriends(fs.items).filter(f=>f.state==='ACCEPTED'));setError('');
  const metadata=await Promise.all(detail.map(async p=>[p.planId,await api<Presentation>(`/api/v1/plans/${p.planId}/presentation`)] as const));
  const votes=await Promise.all(detail.map(async p=>[p.planId,(await api<{items:{actorId:string;state:Rsvp;needsReconfirmation:boolean}[]}>(`/api/v1/plans/${p.planId}/rsvps`)).items] as const));
  if(live){setPresentations(Object.fromEntries(metadata));setRsvps(Object.fromEntries(votes))}
 }catch{if(live)setError(selected?'Нет доступа к этому плану или он недоступен.':'Не удалось загрузить планы')}})();return()=>{live=false}},[tick,selected]);
 const plan=plans?.find(p=>p.planId===selected);const presentation=plan?presentations[plan.planId]:undefined;
 useEffect(()=>{if(!plan?.capabilities.canManage)return;void api<{items:{actorId:string;name:string}[]}>(`/api/v1/plans/${plan.planId}/join-requests`).then(x=>setJoins(x.items)).catch(()=>setJoins([]))},[plan?.planId,tick]);
 useEffect(()=>{if(!plan?.capabilities.canManage)return;void api<{items:{friendId:string;state:string}[]}>(`/api/v1/plans/${plan.planId}/invite-statuses`).then(x=>setInviteStatuses(Object.fromEntries(x.items.map(item=>[item.friendId,item.state])))).catch(()=>setInviteStatuses({}))},[plan?.planId,tick]);
 const selfRsvp=plan&&actor?rsvps[plan.planId]?.find(x=>x.actorId===actor.id)?.state:undefined;
 const needsReconfirmation=Boolean(plan&&actor&&rsvps[plan.planId]?.find(x=>x.actorId===actor.id)?.needsReconfirmation);
 const updateRsvp=async(state:Rsvp)=>{if(!plan)return;try{await apiWrite('PUT',`/api/v1/plans/${plan.planId}/rsvps/me`,{state,expectedReconfirmVersion:presentation?.reconfirmVersion??0});await apiWrite('POST',`/api/v1/plans/${plan.planId}/presentation/seen`,{expectedVersion:presentation?.version??0});setSheet('none');setNotice('Ответ сохранён');setTick(x=>x+1)}catch{setError('Не удалось сохранить ответ. План мог измениться — обновите его.')}};
 const share=async()=>{if(!plan)return;try{let locator:{kind:'PLAN';planId:string}|{kind:'INVITE';inviteRef:string}={kind:'PLAN',planId:plan.planId};if(plan.capabilities.canManage){const x=await api<{inviteRef:string}>(`/api/v1/plans/${plan.planId}/invites`,{expectedStateVersion:plan.stateVersion},crypto.randomUUID());locator={kind:'INVITE',inviteRef:x.inviteRef}}const result=await api<{url:string}>('/api/v1/launch/link',locator);setShareUrl(result.url);setSheet('share')}catch{setError('Не удалось создать ссылку на план')}};
 const copyLink=async()=>{if(!plan)return;try{const result=await api<{url:string}>('/api/v1/launch/link',{kind:'PLAN',planId:plan.planId});await navigator.clipboard.writeText(result.url);setNotice('Ссылка скопирована')}catch{setError('Не удалось скопировать ссылку')}};
 const invite=async(friend:Friend)=>{if(!plan||inviteStatuses[friend.id])return;try{const result=await apiWrite<{state:string}>('POST',`/api/v1/plans/${plan.planId}/invite-friend`,{friendId:friend.id,expectedStateVersion:plan.stateVersion});setNotice(result.state==='SENT'?'Приглашение отправлено':result.state==='PENDING'?'Приглашение уже ожидает ответа':'Друг уже участвует');setInviteStatuses(current=>({...current,[friend.id]:result.state==='SENT'?'PENDING':result.state}));setSheet('none')}catch{setError('Не удалось пригласить друга')}};
 const approve=async(join:{actorId:string;name:string})=>{if(!plan)return;const slot=plan.slots.find(x=>x.state==='UNBOUND');if(!slot){setError('В плане нет свободного места');return}if(presentation?.participantLimit!==null&&presentation?.participantLimit!==undefined&&plan.slots.filter(x=>x.state==='ACTIVE').length>=presentation.participantLimit){setError('Достигнут лимит участников');return}
  try{await api(`/api/v1/plans/${plan.planId}/commands`,{kind:'ROSTER',expectedStateVersion:plan.stateVersion,slots:plan.slots.map(x=>x.slotId===slot.slotId?{...x,actorId:join.actorId,state:'ACTIVE'}:x),rule:plan.rule,decisionDeadline:plan.decisionDeadline,reason:'Одобрен запрос участника'},crypto.randomUUID());setNotice('Участник добавлен');setTick(x=>x+1)}catch{setError('Не удалось добавить участника. Обновите план.')}};
 const cancel=async()=>{if(!plan)return;try{await api(`/api/v1/plans/${plan.planId}/commands`,{kind:'CANCEL',expectedStateVersion:plan.stateVersion,reason:'Организатор отменил план'},crypto.randomUUID());setSheet('none');setTick(x=>x+1)}catch{setError('Не удалось отменить план')}};
 const saveEdit=async()=>{if(!plan||!edit)return;try{const saved=await apiWrite<Presentation>('PUT',`/api/v1/plans/${plan.planId}/presentation`,{title:edit.title,meetingTime:backToIso(meetingInput.current?.value??toLocal(edit.meetingTime)),meetingPoint:edit.meetingPoint,note:edit.note,participantLimit:edit.participantLimit,expectedVersion:edit.version});await apiWrite('POST',`/api/v1/plans/${plan.planId}/presentation/seen`,{expectedVersion:saved.version});setNotice('Изменения сохранены');setSheet('none');setTick(x=>x+1)}catch{setError('Не удалось сохранить план. Обновите данные и попробуйте снова.')}};
 const confirmChange=async()=>{if(!plan)return;try{await apiWrite('POST',`/api/v1/plans/${plan.planId}/presentation/seen`,{expectedVersion:presentation?.version??0});setTick(x=>x+1)}catch{setError('Не удалось подтвердить просмотр изменений')}};
 const selfStatus=(p:Plan)=>actor?rsvps[p.planId]?.find(x=>x.actorId===actor.id)?.state:undefined;
 if(!plans||!actor)return <Frame title="Мои планы" active="plan" onNavigate={onNavigate}>{error?<ErrorState message={error} onRetry={()=>setTick(x=>x+1)}/>:<p role="status">Загружаем планы…</p>}</Frame>;
 if(!plan)return <Frame title="Мои планы" active="plan" onNavigate={onNavigate}>
  {error&&<ErrorState message={error} onRetry={()=>setTick(x=>x+1)}/>}
  {plans.length?<><div className="v2-segment"><button type="button" className={period==='upcoming'?'is-active':''} aria-pressed={period==='upcoming'} onClick={()=>setPeriod('upcoming')}>Предстоящие</button><button type="button" className={period==='past'?'is-active':''} aria-pressed={period==='past'} onClick={()=>setPeriod('past')}>Прошедшие</button></div><div className="v2-plan-list">{plans.filter(p=>{const start=p.options[0]?.terms.startsAt;const upcoming=p.phase!=='CANCELLED'&&(!start||Date.parse(start)>=Date.now());return period==='upcoming'?upcoming:!upcoming}).map(p=><PlanCard key={p.planId} plan={p} presentation={presentations[p.planId]} rsvp={selfStatus(p)} needsReconfirmation={Boolean(actor&&rsvps[p.planId]?.find(x=>x.actorId===actor.id)?.needsReconfirmation)} participantNames={p.slots.filter(s=>s.state==='ACTIVE'&&s.actorId).map(s=>s.actorId===actor.id?actor.displayName:s.actorId===presentations[p.planId]?.organizerId?presentations[p.planId]?.organizerName??'Организатор':friends.find(f=>f.id===s.actorId)?.name??s.label??'Участник')} onOpen={()=>onSelect(p.planId)}/>)}</div>{!plans.some(p=>{const start=p.options[0]?.terms.startsAt;const upcoming=p.phase!=='CANCELLED'&&(!start||Date.parse(start)>=Date.now());return period==='upcoming'?upcoming:!upcoming})&&<EmptyState title={period==='upcoming'?'Предстоящих планов нет':'Прошедших планов нет'} description="Другие планы можно найти в соседней вкладке."/>}</>:<EmptyState title="Пока планов нет" description="Сохраняйте интересные события и планируйте поход с друзьями." action={<PovodButton onClick={()=>onNavigate('search')}>Найти событие</PovodButton>}/>}
 </Frame>;
 const organizerId=presentation?.organizerId??(plan.capabilities.canManage?actor.id:'');
 const participantRows=[...(organizerId?[{id:organizerId,name:presentation?.organizerName??actor.displayName,organizer:true}]:[]),...plan.slots.filter(x=>x.actorId&&x.actorId!==organizerId).map(x=>({id:x.actorId!,name:x.actorId===actor.id?actor.displayName:friends.find(f=>f.id===x.actorId)?.name??x.label??'Участник',organizer:false}))];
 const cancelled=plan.phase==='CANCELLED';
 const sourceRef=plan.options[0]?.source?.ref;
 const eventRoute=sourceRef?{kind:'EVENT' as const,sourceId:sourceRef.provider_id,externalEventId:sourceRef.event_id,occurrenceId:sourceRef.occurrence_id,scope:{kind:'PERSONAL' as const}}:null;
 const inviteableFriends=friends.filter(f=>f.id!==actor.id&&!plan.slots.some(s=>s.actorId===f.id&&s.state==='ACTIVE'));
 return <Frame title={cancelled?'План отменён':'План'} active="plan" onNavigate={onNavigate} onBack={()=>onSelect(null)}>
  {error&&<ErrorState message={error} onRetry={()=>setTick(x=>x+1)}/>}
  {notice&&<p className="v2-feedback" role="status">{notice}</p>}
  <EventSummary plan={plan}/>
  {cancelled?<div className="v2-cancelled"><Icon name="close"/><span><strong>План отменён</strong><small>Организатор отменил совместный поход.</small></span></div>:null}
  {presentation&&(Object.keys(presentation.changedFields).length>0||needsReconfirmation)&&!plan.capabilities.canManage&&!cancelled&&<section className="v2-section v2-changed"><h2>План изменился</h2><p>{needsReconfirmation?'Условия встречи изменились. Ответьте ещё раз, чтобы подтвердить актуальные детали.':'Организатор обновил детали встречи:'}</p>{Object.entries(presentation.changedFields).map(([key,change])=><div className="v2-change-row" key={key}><strong>{changeLabels[key]??key}</strong><span>{changedValue(key,change.from)} → {changedValue(key,change.to)}</span></div>)}{needsReconfirmation?<div className="v2-actions">{(['YES','MAYBE','NO'] as const).map(x=><PovodButton key={x} variant={x==='YES'?'primary':'secondary'} onClick={()=>void updateRsvp(x)}>{rsvpAction[x]}</PovodButton>)}</div>:<PovodButton onClick={()=>void confirmChange()}>Понятно</PovodButton>}</section>}
  <section className="v2-section"><h2>{presentation?.title??plan.title}</h2><div className="v2-card v2-detail-lines"><div><Icon name="calendar"/><span><strong>Событие</strong><small>{date(plan.options[0]?.terms.startsAt??null)}</small></span></div><div><Icon name="pin"/><span><strong>Место события</strong><small>{plan.options[0]?.terms.place??'Уточняется'}</small></span></div><div><Icon name="clock"/><span><strong>Время встречи</strong><small>{presentation?.meetingTime?date(presentation.meetingTime):'Уточняется'}</small></span></div><div><Icon name="pin"/><span><strong>Точка встречи</strong><small>{presentation?.meetingPoint??'Уточняется'}</small></span></div></div>{presentation?.note&&<p className="v2-card v2-note">{presentation.note}</p>}</section>
  {!cancelled&&<section className="v2-section"><h2>Участники ({participantRows.length})</h2><ul className="v2-list">{participantRows.map(row=>{const response=rsvps[plan.planId]?.find(x=>x.actorId===row.id);const state=response?.state;return <li className="v2-person-row" key={row.id}><span className="v2-avatar">{row.name.slice(0,1)}</span><strong>{row.id===actor.id?'Вы':row.name}</strong><StatusChip tone={row.organizer?'violet':response?.needsReconfirmation?'red':state==='YES'?'green':state==='MAYBE'?'violet':'neutral'}>{row.organizer?'Организатор':response?.needsReconfirmation?'Ответить снова':state?state==='YES'&&row.id!==actor.id?'Идёт':rsvpState[state]:'Не ответил'}</StatusChip></li>})}</ul></section>}
  {!cancelled&&plan.capabilities.canManage&&joins.length>0&&<section className="v2-section"><h2>Запросы ({joins.length})</h2>{joins.map(j=><div className="v2-card v2-join" key={j.actorId}><strong>{j.name}</strong><p className="v2-muted">Хочет присоединиться к плану</p><div><PovodButton onClick={()=>void approve(j)}>Добавить</PovodButton><PovodButton variant="secondary" onClick={()=>void apiWrite('POST',`/api/v1/plans/${plan.planId}/joins/${j.actorId}/reject`,{}).then(()=>setTick(x=>x+1)).catch(()=>setError('Не удалось отклонить запрос'))}>Отклонить</PovodButton></div></div>)}</section>}
  {!cancelled&&<div className="v2-actions v2-plan-actions">{plan.capabilities.canManage?<><PovodButton variant="outline" icon="plus" onClick={()=>setSheet('invite')}>Пригласить ещё</PovodButton><PovodButton icon="edit" disabled={!presentation} onClick={()=>{if(presentation){setEdit(presentation);setSheet('edit')}}}>Изменить план</PovodButton></>:<PovodButton onClick={()=>setSheet('rsvp')}>{needsReconfirmation?'Подтвердить ответ':selfRsvp?`Статус: ${selfRsvp==='YES'?'Иду':rsvpState[selfRsvp]}. Изменить`:'Ответить на приглашение'}</PovodButton>}<PovodButton variant="secondary" icon="max" onClick={()=>void share()}>Поделиться в MAX</PovodButton>{presentation&&<CalendarAction plan={plan} presentation={presentation}/>}<PovodButton variant="secondary" icon="copy" onClick={()=>void copyLink()}>Скопировать ссылку</PovodButton>{plan.capabilities.canManage&&<PovodButton variant="outline" onClick={()=>setSheet('cancel')}>Отменить план</PovodButton>}</div>}
  {eventRoute&&onOpenEvent&&<PovodButton variant="secondary" onClick={()=>onOpenEvent(eventRoute)}>Открыть событие</PovodButton>}
  {cancelled&&<PovodButton onClick={()=>onNavigate('search')}>Найти другое событие</PovodButton>}
  <PovodSheet open={sheet==='rsvp'} onClose={()=>setSheet('none')} title="Ты пойдёшь?"><EventSummary plan={plan}/><div className="v2-actions">{(['YES','MAYBE','NO'] as const).map(x=><PovodButton key={x} variant={selfRsvp===x?'primary':'secondary'} onClick={()=>void updateRsvp(x)}>{rsvpAction[x]}</PovodButton>)}</div></PovodSheet>
  <PovodSheet open={sheet==='invite'} onClose={()=>setSheet('none')} title="Пригласить на план"><p className="v2-muted">Выберите друга в Поводе или поделитесь ссылкой в MAX.</p><div className="v2-actions">{inviteableFriends.map(f=>inviteStatuses[f.id]?<div className="v2-person-row" key={f.id}><strong>{f.name}</strong><StatusChip tone="violet">{inviteStatuses[f.id]==='PENDING'?'Ожидает ответа':'Уже участвует'}</StatusChip></div>:<PovodButton variant="secondary" key={f.id} onClick={()=>void invite(f)}>{f.name}</PovodButton>)}{!inviteableFriends.length&&<p className="v2-muted">Все ваши друзья уже участвуют или доступных друзей пока нет.</p>}<PovodButton onClick={()=>void share()}>Поделиться ссылкой</PovodButton></div></PovodSheet>
  <PovodSheet open={sheet==='edit'} onClose={()=>setSheet('none')} title="Редактирование плана">{edit&&<div className="v2-edit-form"><EventSummary plan={plan}/><p className="v2-muted">Дата и место события заданы источником и не редактируются.</p><label className="v2-label">Название плана<input className="v2-input" value={edit.title} maxLength={160} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label className="v2-label">Время встречи<input ref={meetingInput} className="v2-input" type="datetime-local" defaultValue={toLocal(edit.meetingTime)}/></label><label className="v2-label">Точка встречи<input className="v2-input" value={edit.meetingPoint??''} maxLength={200} onChange={e=>setEdit({...edit,meetingPoint:e.target.value})}/></label><label className="v2-label">Заметка<textarea className="v2-textarea" value={edit.note??''} maxLength={2000} onChange={e=>setEdit({...edit,note:e.target.value})}/></label><div className="v2-label">Лимит участников<div className="v2-limit"><button type="button" disabled={(edit.participantLimit??edit.maxParticipants)<=participantRows.length} onClick={()=>setEdit({...edit,participantLimit:Math.max(participantRows.length,(edit.participantLimit??edit.maxParticipants)-1)})}>−</button><strong>{edit.participantLimit??edit.maxParticipants}</strong><button type="button" disabled={(edit.participantLimit??edit.maxParticipants)>=edit.maxParticipants} onClick={()=>setEdit({...edit,participantLimit:Math.min(edit.maxParticipants,(edit.participantLimit??edit.maxParticipants)+1)})}>+</button></div></div><p className="v2-muted">До {edit.maxParticipants} мест в текущем плане.</p><PovodButton onClick={()=>void saveEdit()} disabled={!edit.title.trim()}>Сохранить изменения</PovodButton></div>}</PovodSheet>
  <PovodSheet open={sheet==='cancel'} onClose={()=>setSheet('none')} title="Отменить план?"><EventSummary plan={plan}/><p className="v2-muted">Участники увидят, что план отменён. Это действие нельзя отменить.</p><div className="v2-actions"><PovodButton onClick={()=>void cancel()}>Отменить план</PovodButton><PovodButton variant="secondary" onClick={()=>setSheet('none')}>Оставить план</PovodButton></div></PovodSheet>
  <PovodSheet open={sheet==='share'} onClose={()=>setSheet('none')} title="Поделиться планом в MAX"><p className="v2-muted">План и актуальные детали останутся в Поводе.</p><EventSummary plan={plan} people={participantRows.map(row=>row.name)}/><div className="v2-actions"><PovodButton icon="max" onClick={()=>void shareOrCopy('Приглашение в план в Поводе',shareUrl,()=>{setSheet('none');setNotice('Открыт выбор получателя в MAX.')},()=>setError('MAX недоступен. Скопируйте ссылку.'))}>Отправить в MAX</PovodButton><PovodButton variant="secondary" icon="copy" onClick={()=>void navigator.clipboard.writeText(shareUrl).then(()=>{setSheet('none');setNotice('Ссылка скопирована')}).catch(()=>setError('Не удалось скопировать ссылку'))}>Скопировать ссылку</PovodButton></div></PovodSheet>
 </Frame>;
}
