import fs from 'node:fs';
const update=(p,fn)=>fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));
update('README.md',s=>s.replace(/\*\*Текущий T102\.1:\*\*[^\r\n]*/, '**Текущий T102.2: T102 PASS.** Install/metadata/syntax/unit 115/115/typecheck/build, clean Docker build 25,132 с, startup, host/internal health и stop/restart прошли. API опубликован только на 127.0.0.1:3000; PostgreSQL/Redis остаются в internal backend без host ports. [Актуальный handoff](docs/handoffs/T102_2_NETWORK_MIGRATION_ACCEPTANCE.md), [evidence](artifacts/t102_2/FINAL_VERIFICATION.json). Следующие tickets не активированы.')
.replace(/Docker daemon доступен\.[^\r\n]*/, 'Docker daemon доступен. В T102.2 проверены clean build, startup и stop/restart. Windows host получает 200 от live/ready; внутренние live/ready/HTML тоже проходят. API подключён к обычной bridge-сети frontend и internal-сети test (backend). Настройки системы не менялись.')
.replace('Сеть `internal: true`; внешняя отправка', 'PostgreSQL, Redis, worker и служебные контейнеры используют только сеть `test` с `internal: true`. Только API дополнительно использует `frontend` и получает обычный bridge egress; внешняя отправка')
.replace('**Реальные container versions не наблюдались.**', 'В T102.2 наблюдены Node 24.20.0, npm 11.19.0, PostgreSQL 18.6, Redis 8.2.9, BullMQ 6.3.4 и ioredis 5.11.1.')
.replace('Проверка доступа с host (в T102.1 FAIL из-за отсутствующего mapping):','Проверка доступа с host (T102.2 PASS до и после restart):')
.replaceAll('http://localhost:3000/health/','http://127.0.0.1:3000/health/')
.replace('Измерение T102.1: clean `docker compose --progress plain build --no-cache` — 24,759 с','Измерение T102.2: clean `docker compose --progress plain build --no-cache` — 25,132 с')
.replace('в `artifacts/t102_1/`.','в `artifacts/t102_2/`.')
.replace('Следующий шаг — human review сетевой изоляции/host-доступа. Компилятор и внутренний Docker runtime проверены.','T102 завершён: компилятор, Docker runtime и host-доступ проверены. Следующий шаг — human review и отдельная активация следующего ticket.'));
fs.writeFileSync('docs/tasks/ACTIVE_TASK.md',`# Active task\n\n**No implementation ticket active. T102.2 complete; stopped for human review.**\n\n- T101: PASS.\n- T102: PASS — [handoff](../handoffs/T102_2_NETWORK_MIGRATION_ACCEPTANCE.md), [evidence](../../artifacts/t102_2/FINAL_VERIFICATION.json).\n- T102.2 was explicitly authorized: migration safety resolved, minimal dual-network fix, clean install/build/start/host health/restart verified.\n- T103 prerequisite from T102 is cleared; queue decision still BLOCKED pending T103 verification. T103 is NOT STARTED or automatically activated.\n- T104/T105/T106 and later tickets NOT STARTED; provider/rights and MAX/client gates remain.\n- One writer/integration owner. Historical prompts do not activate work.\n`);
update('docs/tasks/102_DEPENDENCY_BUILD_BASELINE.md',s=>s.replace(/^Status:.*$/m,'Status: PASS after T102.2; stopped for human review. Current evidence: docs/handoffs/T102_2_NETWORK_MIGRATION_ACCEPTANCE.md. Prior T102/T102.1 evidence preserved.'));
update('docs/current/PROJECT_STATE.md',s=>s.replace(/T101 PASS\. T102\.1[^\r\n]*/,'T101 PASS. T102 PASS after T102.2: reproducible install, metadata, syntax, unit 115/115, strict typecheck/build; clean Docker build 25.132 s, startup, internal and host health, stop/restart pass. PostgreSQL/Redis remain internal and unpublished. Migration 0002 classified SAFE_PRE_RELEASE_EDIT on available repository evidence. See [current handoff](../handoffs/T102_2_NETWORK_MIGRATION_ACCEPTANCE.md). T103 prerequisites from T102 cleared; queue decision remains BLOCKED pending T103. No next ticket active.'));
update('docs/current/KNOWN_GAPS.md',s=>s.replace(/- T102\.1:[^\r\n]*/,'- T102: PASS after T102.2 (115/115 unit; strict typecheck/build; clean Docker build 25.132 s; startup, host/internal health and restart). Local API loopback mapping fixed; PostgreSQL/Redis stay internal and unpublished. Declaration patch remains guarded technical debt. See [handoff](../handoffs/T102_2_NETWORK_MIGRATION_ACCEPTANCE.md).').replace('T102.1 clean Docker build meets <=5 minutes; host access still blocked.','T102.2 clean Docker build meets <=5 minutes; local host access PASS. Public deployment remains a separate gate.'));
