import fs from 'node:fs';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const dir='artifacts/t102_1/';
const files=execFileSync('git',['-c','safe.directory=D:/Dev/Repos/The-Boys-Max','ls-files','--cached','--others','--exclude-standard','-z'],{encoding:'utf8'}).split('\0').filter(x=>x&&!x.startsWith(dir));
const hashes=Object.fromEntries(files.filter(f=>fs.existsSync(f)).map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]));
fs.writeFileSync(dir+'STARTING_HASHES.json',JSON.stringify(hashes,null,2));
const lock=JSON.parse(fs.readFileSync('package-lock.json','utf8'));
const metadata={};for(const name of Object.keys({...lock.packages[''].dependencies,...lock.packages[''].devDependencies})){const p=JSON.parse(fs.readFileSync(`node_modules/${name}/package.json`,'utf8'));metadata[name]={locked:lock.packages['node_modules/'+name],version:p.version,engines:p.engines,peerDependencies:p.peerDependencies,peerDependenciesMeta:p.peerDependenciesMeta,type:p.type,main:p.main,types:p.types,exports: name==='drizzle-orm'?Object.fromEntries(Object.entries(p.exports).filter(([k])=>['.','./node-postgres','./pg-core'].includes(k))):p.exports};}
fs.writeFileSync(dir+'DEPENDENCY_CONTRACTS.json',JSON.stringify(metadata,null,2));
const classify=line=>!line.startsWith('node_modules/')?line.includes('ioredis')||/^(apps\/worker|packages\/platform\/governor|scripts\/arm-test-outbound|tests\/)/.test(line)?'D/B: ioredis named export':line.includes('TS18046')?'C/E: Fastify unknown error':line.startsWith('apps/api')?'C/F: HTTP Amount union':'C: Leaflet indexed access':line.includes('TS2307')?'A/E: optional dialect peers':line.includes('TS2344')?'A: protected session in public keyof':line.includes('roles.d.ts')?'A: stripped role config fields':line.includes('columns/enum')?'A: throwing enum method return':line.includes('columns/')?'A: stripped generatedAlwaysAs':'A: stripped getSQL';
let report='# T102.1 root cause analysis (before edits)\n\nStarting SHA: 4f9a198d4fa2b18686efa19a59b6ac78281d341d. TS 5.9.3, Node typings 24.13.3. strict=true, skipLibCheck=false, module/moduleResolution=NodeNext.\n\n';
const groups={};const diagnostics={};for(const stage of ['typecheck','build']){const lines=fs.readFileSync(dir+'logs/'+stage+'-before.txt','utf8').split(/\r?\n/).filter(l=>/error TS\d+/.test(l));diagnostics[stage]=lines.map(line=>({root:classify(line),line}));for(const {root} of diagnostics[stage]){groups[root]??={typecheck:0,build:0};groups[root][stage]++;}}
report+='| Category / root cause | Typecheck | Build |\n|---|---:|---:|\n'+Object.entries(groups).map(([k,v])=>`| ${k} | ${v.typecheck} | ${v.build} |`).join('\n');
report+='\n\nB is secondary to D: no independent NodeNext compiler configuration defect identified. G: 0. Each primary diagnostic counted once; indented explanation lines are not additional diagnostics. Drizzle common column-builder imports every dialect, so 70 diagnostics cascade from this graph even for PostgreSQL-only usage.\n\nMinimum source corrections: named Redis export (11/5 use-site errors); narrow unknown error fields (6); use discriminated Amount schema with existing canonical validator (1); test coordinate before setView (1). Domain Price unchanged.\n\nDrizzle repairs to investigate: restore stripped runtime members; exclude protected session from public method exclusion unions; type throwing enum method as never; install actual optional peer types only if unavoidable. Do not change compiler settings or runtime SQL architecture. Current declarations are defective, so skipLibCheck does not satisfy the requested correct-declarations exception.\n\nSources: https://github.com/drizzle-team/drizzle-orm/issues/5187 ; https://github.com/drizzle-team/drizzle-orm/issues/4818 ; https://github.com/redis/ioredis ; https://www.typescriptlang.org/docs/handbook/esm-node.html . Local exact package contracts: DEPENDENCY_CONTRACTS.json. Installed JS and source maps are the pinned runtime evidence.\n';
fs.writeFileSync(dir+'ROOT_CAUSE_ANALYSIS.md',report);fs.writeFileSync(dir+'COMPILER_DIAGNOSTICS.json',JSON.stringify(diagnostics,null,2));
console.log(report);
