import {upgradePricePlan} from '../../packages/domain/price-upgrade.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {syntheticCandidate,itemizedPrice} from '../catalog-fixtures.ts';
import {O,A,P,OID,SID,NOW,DEC,COM,terms,self} from '../fixtures.ts';
import {evaluateEligibility} from '../../modules/search/core/eligibility.ts';
import {parsePrice,priceFromQuote} from '../../modules/search/core/price.ts';
import {context,defaultIntent,blankDraft,fromUiDraft,priceView,geoView,sourceSnapshot,candidateTerms,uniqueInstant,fromAiCandidate} from '../../modules/integration/projections.ts';
import {createPlan,apply,current,capabilities,complete} from '../../packages/domain/plan.ts';
import {noticeExpiry,noticeStillCurrent} from '../../packages/domain/notices.ts';
import {launchLink,decodeLaunch} from '../../packages/platform/links.ts';
import {canonical} from '../../modules/search/core/guard.ts';
import {draftForManualConfirmation} from '../../modules/search/core/search.ts';
import {confirmSearch,assertIssuedApproval} from '../../modules/search/core/authority.ts';
import {emptyIntent,manualCandidate,strictJson} from '../../modules/ai/provider/validation.ts';
import type {IssuancePort} from '../../modules/search/core/issuance.ts';
import type {Approval,Capability,Subject,SearchScope,PolicyPort} from '../../modules/search/core/types.ts';
const ctx=context(NOW);
function selected(){let p=createPlan(P,O,'SYNTHETIC',[self],{kind:'ALL'},DEC,COM,NOW);
 const step=(c:Record<string,unknown>)=>{p=apply(p,O,{...c,expectedStateVersion:p.stateVersion} as Parameters<typeof apply>[2],NOW);};
 step({kind:'ADD_OPTION',optionId:OID,snapshotId:randomUUID(),terms});step({kind:'START'});step({kind:'RESPOND',optionId:OID,termsRevision:1,value:'CAN'});step({kind:'SELECT',optionId:OID,allowProvisional:false,reason:''});return p;}
for(const [name,start,end,expected,reason] of [
 ['ended','2026-09-15T10:00:00Z','2026-09-15T12:00:00Z','FAIL','OCCURRENCE_ENDED'],
 ['end equality','2026-09-16T09:00:00Z',NOW,'FAIL','OCCURRENCE_ENDED'],
 ['upcoming','2026-09-20T10:00:00Z','2026-09-20T12:00:00Z','PASS','OCCURRENCE_UPCOMING'],
 ['already started, end missing','2026-09-16T09:00:00Z',null,'UNKNOWN','START_PASSED_END_UNKNOWN'],
 ['ongoing','2026-09-16T09:00:00Z','2026-09-16T12:00:00Z','UNKNOWN','ONGOING_ENTRY_UNVERIFIED']
] as const)test('PC001 '+name,()=>{const c=structuredClone(syntheticCandidate());c.starts_at=start;c.ends_at=end;const e=evaluateEligibility(defaultIntent(),c,ctx);assert.equal(e.status,expected);assert.ok(e.checks.some(c=>c.reason===reason));});
test('PC001 cancelled future event cannot pass',()=>{const c=structuredClone(syntheticCandidate());c.status='CANCELLED';assert.equal(evaluateEligibility(defaultIntent(),c,ctx).status,'FAIL');});
test('PC002 cancellation after commitment deadline gets future informational TTL',()=>{const p=selected(),now='2026-09-19T10:00:00Z';assert.equal(noticeExpiry(p,'CANCELLATION',now),'2026-09-19T11:00:00.000Z');assert.equal(noticeExpiry(p,'TERMS_CHANGED',now),'2026-09-19T11:00:00.000Z');assert.equal(noticeExpiry(p,'SELECTION',now),null);assert.equal(noticeExpiry(p,'REMINDER',now),null);});
test('PC002 cancellation cannot be delivered at/after event start',()=>{const p=selected();assert.equal(noticeExpiry(p,'CANCELLATION',terms.startsAt!),null);});
test('PC002 stale selection, terminal and legacy notice guards',()=>{const p=selected();assert.equal(noticeStillCurrent(p,'SELECTION',p.selectionRevision,1),true);assert.equal(noticeStillCurrent(p,'SELECTION',99,1),false);assert.equal(noticeStillCurrent(p,'LEGACY',null,null),false);p.phase='CANCELLED';assert.equal(noticeStillCurrent(p,'SELECTION',p.selectionRevision,1),false);assert.equal(noticeStillCurrent(p,'CANCELLATION',0,0),true);});
test('PC003 500+30 remains 530 across JSON, domain validation and UI projection',()=>{const c=syntheticCandidate(),p=itemizedPrice();assert.deepEqual(parsePrice(JSON.parse(JSON.stringify(p))),p);const t=candidateTerms(c,ctx);assert.equal(complete(t),true);const q=apply(createPlan(P,O,'Test',[self],{kind:'ALL'},DEC,COM,NOW),O,{kind:'ADD_OPTION',optionId:OID,snapshotId:SID,expectedStateVersion:1,terms:t},NOW);assert.deepEqual(current(q.options[0]!).terms.price,p);assert.equal(priceView(p).totalLabel,'530 ₽');assert.equal(priceView(p).fees_known,true);});
test('PC003 unknown required fees are not turned into zero or a complete price',()=>{const p=priceFromQuote({kind:'EXACT',exact_minor:'50000',basis:'PER_PERSON',currency:'RUB',fees_known:false,fee_mode:'UNKNOWN'},'unknown');assert.equal(p.base_price.knownness,'KNOWN');assert.equal(p.total_price.knownness,'UNKNOWN');assert.equal(priceView(p).totalLabel,null);assert.equal(complete({...terms,price:p}),false);assert.ok(p.warnings.some(w=>w.code==='MANDATORY_FEES_UNKNOWN'));});
test('PC003 forged total rejected; included quote not double charged',()=>{const p=structuredClone(itemizedPrice());if(p.total_price.knownness==='KNOWN'&&p.total_price.amount.kind==='EXACT')p.total_price.amount.exact_minor='56000';assert.throws(()=>parsePrice(p),/PRICE_DERIVATION_MISMATCH/);const q=priceFromQuote({...itemizedPrice().source_quote,fee_mode:'INCLUDED',exact_minor:'53000'},'included');assert.equal(priceView(q).totalLabel,'530 ₽');assert.equal(q.quoted_amount_role,'ALL_IN');});
test('PC004 19 venue -> 21 null name/city projection and blocked external maps',()=>{const c=syntheticCandidate(),g=geoView(c,ctx);assert.equal(g.geo.venue,null);assert.equal(g.geo.city,'Москва');assert.equal(g.geo.address,c.venue.address);assert.deepEqual(g.disclosure,{basemap:'BLOCK',navigation:'BLOCK'});assert.equal(g.geo.position,null);});
test('SOLO context-only count and no-cinema filters do not create group authority',()=>{const d={...blankDraft(),participants:'4',excludeCategories:['CINEMA'],budgetText:'530',priceBasis:'PER_PERSON' as const};const h=fromUiDraft(d,ctx);assert.equal(h.interested_count,4);assert.deepEqual(h.inventory_requirement,{kind:'NOT_REQUESTED'});assert.deepEqual(h.excluded_categories,['CINEMA']);assert.equal(h.budget?.max_minor,'53000');assert.equal('slots' in h,false);assert.equal('plan_id' in h,false);});
test('literal catalog text does not mutate hard structured intent and is bounded',()=>{assert.deepEqual(fromUiDraft({...blankDraft(),text:'без кино'},ctx),fromUiDraft(blankDraft(),ctx));assert.throws(()=>fromUiDraft({...blankDraft(),text:'x'.repeat(121)},ctx),/SEARCH_TEXT_TOO_LONG/);});
test('budget with unknown basis is clarification, not pass',()=>assert.throws(()=>fromUiDraft({...blankDraft(),budgetText:'1000'},ctx),/PRICE_BASIS_REQUIRED/));
test('source snapshot contains no personal query/history; changing time preserves source and appends',()=>{const c=syntheticCandidate(),source=sourceSnapshot(c);assert.equal('hard' in source,false);assert.equal('interested_count' in source,false);let p=selected();current(p.options[0]!).source=source;const old=JSON.stringify(current(p.options[0]!));p=apply(p,O,{kind:'EDIT_OPTION',optionId:OID,snapshotId:randomUUID(),terms:{...terms,startsAt:'2026-09-20T16:00:00.000Z'},cosmetic:false,reason:'Explicit edit',expectedStateVersion:p.stateVersion},NOW);assert.equal(JSON.stringify(p.options[0]!.snapshots[0]),old);assert.deepEqual(current(p.options[0]!).source,source);assert.equal(current(p.options[0]!).terms.startsAt,'2026-09-20T16:00:00.000Z');});
test('organizer without participation has authority, no automatic active slot',()=>{const p=createPlan(P,O,'Test',[{...self,actorId:null,state:'UNBOUND'}],{kind:'ALL'},DEC,COM,NOW);assert.equal(capabilities(p,O).canManage,true);assert.equal(capabilities(p,O).canRespond,false);assert.equal(capabilities(p,A).canRead,false);});
test('wall time conversion rejects fold, gap and invalid day; valid date exact',()=>{assert.equal(uniqueInstant('2026-09-20T19:00','Europe/Moscow'),'2026-09-20T16:00:00.000Z');for(const t of ['2026-10-25T02:30','2026-03-29T02:30','2026-02-31T12:00'])assert.throws(()=>uniqueInstant(t,'Europe/Berlin'),/LOCAL_TIME/);});
test('deep links are locators only and do not contain tokens or actor data',()=>{const url=launchLink({kind:'PLAN',planId:P},{mode:'test',botUsername:'test_bot',publicOrigin:'https://test.invalid'});assert.equal(new URL(url).hostname,'max.ru');assert.ok(!url.includes(O));assert.deepEqual(decodeLaunch('p_'+P),{kind:'PLAN',planId:P});assert.deepEqual(decodeLaunch('p_'+P+'x'),{kind:'PERSONAL'});});
/** File-backed port is an OFFLINE CONTRACT TEST, not the production PG adapter or a queue. */
test('durable approval contract survives new service object; foreign/expired/mutated rejected',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'w26-approval-'));const file=join(dir,'receipt.json'),subject:Subject={actor_id:O,session_id:SID},scope:SearchScope={kind:'PERSONAL',search_context_id:P};
 const cap:Capability={actor_id:O,scope,binding:{acl_revision:1,search_context_revision:1,plan:null},actions:['SEARCH','CONFIRM_SEARCH'],session_active:true,expires_at:COM,external_enabled:false,policy_version:'OFFLINE_TEST_ONLY'};
 function port():IssuancePort{return {saveApproval:async(a,s,expiresAt)=>writeFile(file,JSON.stringify({a,s,expiresAt})),loadApproval:async(id,s,now)=>{const r=JSON.parse(await readFile(file,'utf8'));return r.a.approval_id===id&&canonical(r.s)===canonical(s)&&Date.parse(r.expiresAt)>Date.parse(now)?r.a:null;},saveOffer:async()=>{throw Error('NOT_USED');},loadOffer:async()=>null};}
 try{const d=draftForManualConfirmation(defaultIntent()),policy:PolicyPort={load:async()=>cap};const a=await confirmSearch(d,{action:'CONFIRM_SEARCH',approval_id:OID,expected_binding:cap.binding,expected_draft_json:canonical(d)},subject,scope,policy,ctx,port());await assertIssuedApproval(JSON.parse(JSON.stringify(a)),subject,ctx,port());await assert.rejects(assertIssuedApproval(a,{...subject,actor_id:A},ctx,port()),/UNTRUSTED/);await assert.rejects(assertIssuedApproval(a,subject,context(COM),port()),/UNTRUSTED/);await assert.rejects(assertIssuedApproval({...a,approval_id:randomUUID()},subject,ctx,port()),/UNTRUSTED/);}finally{await rm(dir,{recursive:true,force:true});}
});
test('AI20 candidate remains an explicit-confirmation draft; no tool side effect',()=>{const intent={...emptyIntent(),party_size:4,require_available:true,excluded_categories:['CINEMA' as const]};const pc={local_date:'2026-09-16',timezone:null,cities:[{id:'msk',label:'Москва',timezone:'Europe/Moscow'}]};const v=manualCandidate(intent,pc);assert.ok(v.candidate);const d=fromAiCandidate(v.candidate,pc,ctx);assert.equal(d.state,'DRAFT');assert.equal(d.intent.interested_count,4);assert.deepEqual(d.intent.inventory_requirement,{kind:'AT_LEAST',quantity:4});assert.equal('approval_id' in d,false);});
for(const raw of ['{"x":1,"x":2}','{"x":1,"\\u0078":2}','{"__proto__":{}}'])test('AI strict JSON rejects '+raw,()=>assert.throws(()=>strictJson(raw)));

test('price migration preserves legacy input and stales consent without rewriting immutable SQL rows',()=>{const p=selected(),old=structuredClone(p) as unknown as {version:string;options:{snapshots:{terms:{price:unknown}}[]}[]};old.version='max.backend.23.v1-candidate';for(const o of old.options)for(const s of o.snapshots)s.terms.price={knownness:'KNOWN',basis:'PER_PERSON',currency:'RUB',amount:{kind:'EXACT',exact_minor:'50000',min_minor:null,max_minor:null},extras:[]};const before=JSON.stringify(old),r=upgradePricePlan(old)!;assert.equal(JSON.stringify(old),before);assert.equal(r.plan.selectionRevision,p.selectionRevision+1);assert.equal(r.newSnapshots.length,1);assert.equal(current(r.plan.options[0]!).terms.price.fees_known,false);assert.equal(current(r.plan.options[0]!).terms.price.total_price.knownness,'UNKNOWN');assert.equal(upgradePricePlan(r.plan),null);});
