import fs from 'node:fs';import path from 'node:path';import {out,run,save,head,hash} from './verification-lib.mjs';
const marker='SYNTHETIC_MAX_INTEGRATION_EXCLUDED_MARKER_20260920';
const forbidden=['.secrets/integrated-marker.txt','.env.integrated-marker','docs/integrated-marker.md','docs/research/integrated-marker.txt','input/integrated-marker.txt','artifacts/raw/integrated-marker.txt','artifacts/research/integrated-marker.zip','input/design/integrated-marker.png','node_modules/integrated-marker.txt','dist/integrated-marker.js','coverage/integrated-marker.txt','private.log','apps/api/.secrets/integrated-marker','apps/api/.env.integrated-marker','apps/api/node_modules/integrated-marker','apps/miniapp/dist/integrated-marker.js','apps/miniapp/test-results/integrated-marker.png','apps/api/integrated-marker.zip','apps/api/integrated-marker.sqlite','apps/api/integrated-marker.tmp','apps/api/logs/integrated-marker.txt','apps/miniapp/screenshots/integrated-marker.png','scripts/research/integrated-marker.tar.gz','apps/miniapp/input/integrated-marker.txt','packages/domain/docs/integrated-marker.md','scripts/artifacts/integrated-marker.txt'];
for(const p of forbidden){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,marker,{flag:'wx'});}
const dest=path.resolve(out,'context-export');if(fs.existsSync(dest))throw new Error('FRESH_CONTEXT_EXPORT_REQUIRED');
fs.writeFileSync(out+'/Context.Dockerfile','FROM scratch\nCOPY . /context/\n');
run('docker-context','docker',['build','--no-cache','--progress=plain','-f',out+'/Context.Dockerfile','--output','type=local,dest='+dest,'.']);
const required=['package.json','package-lock.json','.npmrc','tsconfig.json','apps/api/app.ts','packages/platform/transport.ts','scripts/copy-assets.mjs','migrations','licenses','certs/russian-trusted-root-ca.crt'];
const leaked=[...forbidden,'.git'].filter(p=>fs.existsSync(path.join(dest,'context',p))),missing=required.filter(p=>!fs.existsSync(path.join(dest,'context',p)));
save('DOCKER_CONTEXT.json',{sourceSha:head(),policySource:'1176eb3ae7e84315b9c3f0107c19232c8b2cffc4',dockerignoreSha256:hash(fs.readFileSync('.dockerignore')),marker,forbidden:[...forbidden,'.git'],required,leaked,missing,status:leaked.length||missing.length?'FAIL':'PASS'});if(leaked.length||missing.length)throw new Error('CONTEXT_FAILED');
const sha=head(),timestamp=new Date().toISOString(),tag='povod-max-integrated:'+sha.slice(0,8);
run('docker-release-build','docker',['build','--no-cache','--progress=plain','--target','release','--build-arg','SOURCE_SHA='+sha,'--build-arg','BUILD_TIMESTAMP='+timestamp,'--iidfile',out+'/image-id.txt','-t',tag,'.']);
const id=fs.readFileSync(out+'/image-id.txt','utf8').trim();
const info=JSON.parse(run('docker-image-identity','docker',['image','inspect',id,'--format','{{json .}}']));
const version=JSON.parse(run('docker-runtime-versions','docker',['run','--rm',id,'node','-e','console.log(JSON.stringify({node:process.version,openssl:process.versions.openssl,platform:process.platform,arch:process.arch}))']));
const base=JSON.parse(run('docker-base-identity','docker',['image','inspect','node:24.20.0-bookworm-slim@sha256:ba849c60be29959425b8734d57b8b4b7d56f98edd9504c9af091d5281095a71e','--format','{{json .}}']));
save('EXACT_IMAGE.json',{sourceSha:sha,imageId:id,imageDigests:info.RepoDigests,tag,created:info.Created,buildTimestamp:timestamp,baseImageId:base.Id,baseImageDigests:base.RepoDigests,baseReference:'node:24.20.0-bookworm-slim@sha256:ba849c60be29959425b8734d57b8b4b7d56f98edd9504c9af091d5281095a71e',runtime:version,labels:info.Config.Labels});
for(const p of forbidden){if(fs.readFileSync(p,'utf8')!==marker)throw new Error('MARKER_CHANGED');fs.unlinkSync(p);}console.log(JSON.stringify({status:'BUILT',imageId:id}));
