import fs from 'node:fs';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const base='artifacts/t103';
const commands=JSON.parse(fs.readFileSync(`${base}/COMMAND_RESULTS.json`,'utf8').replace(/^\uFEFF/,''));
const required=['verify-dependencies','patch-guards','syntax-final','unit','typecheck','build','docker-final-build','runtime-final','integration-final','staged-diff-final','secret-prohibited-final'];
for(const name of required)assert.equal(commands.findLast(c=>c.name===name)?.exit_code,0,name);
const testedSources=JSON.parse(fs.readFileSync(`${base}/logs/runtime-final-source.json`,'utf8').replace(/^\uFEFF/,''));
for(const [path,hash] of Object.entries(testedSources))assert.equal(createHash('sha256').update(fs.readFileSync(path)).digest('hex'),hash,`Source changed after final runtime: ${path}`);
const full=fs.readFileSync(`${base}/logs/runtime-final.txt`,'utf8');
const scenarios=full.split(/\r?\n/).filter(s=>s.startsWith('T103_RESULT ')).map(s=>JSON.parse(s.slice(12)));
assert.equal(scenarios.length,17);for(const s of scenarios)assert.equal(s.status,'PASS',s.name);
const integration=fs.readFileSync(`${base}/logs/integration-final.txt`,'utf8');assert.match(integration,/tests 16/);assert.match(integration,/pass 16/);assert.match(integration,/fail 0/);
const git=(...args)=>{const r=spawnSync('git',args,{encoding:'utf8'});assert.equal(r.status,0);return r.stdout.trim();};
assert.equal(git('branch','--show-current'),'codex/t103-bullmq-runtime');
const checkList=commands.map(c=>({name:c.name,command:c.command,exit_code:c.exit_code,duration_seconds:c.duration_seconds,log:c.log,source_manifest:c.source_manifest}));
const verification={task:'T103',status:'PASS',queue_decision:'KEEP_EXISTING_BULLMQ',starting_baseline:'5e4973f24fb74489387b3c29313cfcd1e8401ca7',branch:'codex/t103-bullmq-runtime',tested_head_before_commit:git('rev-parse','HEAD'),resulting_commit:{resolution:'git log -1 --format=%H -- artifacts/t103/FINAL_VERIFICATION.json',literal_post_commit_receipt:'.run-evidence/t103-final-commit.json',reason:'A tracked file cannot contain the SHA of its own containing commit.'},integration:{initial:{tests:14,passed:11,failed:3,skipped:0},final:{tests:16,passed:16,failed:0,skipped:0}},runtime:{source_hashes_match_final:true,final_total:17,passed:17,failed:0,scenarios},regression:{unit:'115/115 PASS',typecheck:'PASS',syntax:'PASS',build:'PASS',docker_build:'PASS',dependencies:'PASS; pinned versions and lock unchanged; 15 Drizzle after hashes verified'},code_fix:'Raw Drizzle invite expires_at is a string: convert to Date for create/replay expiry checks and ISO serialization. No queue, retry, concurrency, governor or schema change.',checks:checkList,not_run:['Real MAX sends or delivery receipts','Provider ingestion/rights/data acceptance','Real MAX mobile/web/auth/client acceptance','Host power loss, Redis disk corruption or PostgreSQL volume loss','Long-running load/fairness soak and all distributed partitions','Release deployment or T107 implementation'],risks:['UNKNOWN conservatively suppresses resend and may represent an unsent message.','Governor state loss requires fresh epoch, warm hold and worker restart; do not auto-unlimit.','Redis AOF everysec is not zero-loss; PG outbox recovers pending intent.','Observed stalled-job recovery about 62–93 seconds.','Worker start without PG exits 1; explicit restart/supervision is required. Running worker recovery is proven separately.','Readiness remains 200 on Redis-only outage; it is not queue-health evidence.','TestTransport acceptance does not prove real MAX/user delivery.'],t107:'No T103 queue blocker. Other tickets and provider/normalization gates are not accepted by this evidence.',next_action:'Human review/integration of this branch only. STOP; no next ticket, push or merge.'};
fs.writeFileSync(`${base}/FINAL_VERIFICATION.json`,JSON.stringify(verification,null,2)+'\n');
const descriptions={
 'normal-job':'Production worker reconciles one durable effect, one receipt.',
 'duplicate':'Sequential webhook replay and distinct Bull jobs: one attempt/receipt.',
 'concurrent-duplicate':'8 simultaneous webhook duplicates and 8 Bull jobs: one attempt/receipt; IT-14 additionally covers SELECT command replay.',
 'worker-before':'SIGKILL at active Bull job before deliver; stalled retry/reconciliation -> one successful effect.',
 'worker-during':'SIGKILL after transport receipt but before final DB commit -> UNKNOWN, one receipt, no resend.',
 'worker-after-db-before-ack':'SIGKILL after SUCCEEDED commit while Bull job still active -> stalled job completes with no second attempt/receipt.',
 'worker-restart':'Durable QUEUED effect consumed after worker start; second restart does not resend.',
 'poison-job':'Safe retry transport yields 5 attempts, real >=1000ms gaps, DEAD/RETRY_BUDGET_EXHAUSTED; no sixth attempt.',
 'malformed-job':'Production processor rejects invalid outboxId; Bull attemptsMade=1, retained failed job, no infinite retry.',
 'redis-loss':'Real Redis stop; API commits intent, governor fails closed; existing worker reconnects and PG reconciles one delivery.',
 'redis-restart':'Scoped queue/key deletion + real Redis SIGKILL/start; PG survives, no silent send, explicit existing re-arm script installs fresh epoch/10s hold, restarted worker recovers.',
 'pg-failure':'PG stop: webhook503, worker startup exits1. PG/start + worker restart recovers pending intent.',
 'pg-active-failure':'PG outage combined with kill during possible submission -> UNKNOWN, one receipt.',
 'pg-live-failure':'Running production worker stays alive across PG outage and resumes delivery after PG recovery.',
 'pg-final-commit-failure':'Transport receipt persisted; actual PG stop prevents final commit; failed Bull job recovers durable RUNNING to UNKNOWN without resend.',
 'graceful-shutdown':'SIGTERM during actual blocked receipt INSERT: worker waits, completes after lock release, exits0.',
 'governor':'Actual Redis8.2.9 Lua: measured destination/global gaps, restart persistence, missing epoch HOLD, no unlimited fallback.'};
let matrix='# T103 failure matrix\n\nBaseline `5e4973f24fb74489387b3c29313cfcd1e8401ca7`; branch `codex/t103-bullmq-runtime`. Final run: 17/17 PASS with PostgreSQL18.6, Redis8.2.9, BullMQ6.3.4, ioredis5.11.1. All transport effects are SYNTHETIC.\n\n| Scenario | Result | Seconds | Actual proof | Receipt |\n|---|---|---:|---|---|\n';
for(const s of scenarios)matrix+=`| ${s.name} | ${s.status} | ${(s.duration_ms/1000).toFixed(3)} | ${descriptions[s.name]} | [JSON](logs/${s.name}.txt) |\n`;
matrix+='\nHistorical failures: initial integration 11/14 due to Drizzle raw invite timestamp mapping (IT-13 before FAIL, after PASS); initial runtime14/15 due to an abandoned waiter in the new governor test (corrected test, production Lua unchanged). Full initial/final logs and source hashes are retained. Final integration16/16 includes 8-way duplicate SELECT receipt/outbox/delivery proof.\n\nLimits: Redis data loss is scoped queue/key removal plus real container crash, not destruction of a disk/volume. Live MAX sends, actual delivered-to-user status, disk corruption, sustained load and arbitrary partitions are unproven. UNKNOWN is a correct conservative terminal result, not successful delivery. Queue contents alone are never the business correctness boundary. PG-only health readiness remains200 during Redis outage.\n';
fs.writeFileSync(`${base}/FAILURE_MATRIX.md`,matrix);
const checkText=required.map(n=>{const c=commands.findLast(c=>c.name===n);return `- ${n}: exit ${c.exit_code}, ${c.duration_seconds.toFixed(3)}s; ${c.log}`;}).join('\n');
fs.writeFileSync('docs/handoffs/T103_BULLMQ_RUNTIME.md',`# T103 — BullMQ runtime verification\n\n**PASS; QUEUE_DECISION = KEEP_EXISTING_BULLMQ. Stop after this ticket for human review.**\n\nInputs/revision: user-authorized isolated worktree D:/Dev/Repos/The-Boys-Max-t103, branch codex/t103-bullmq-runtime, clean starting SHA 5e4973f24fb74489387b3c29313cfcd1e8401ca7. Read AGENTS, ACTIVE_TASK, BASELINE_PARALLEL, T102.2 acceptance, preflight queue/gap matrix, current authority, ADR-003 and FINAL SCOPE FREEZE. Historical T102 stop text is superseded only by this explicit T103 activation. No main/parallel worktree changes, global Git changes, push or merge.\n\nExisting architecture remains PostgreSQL outbox/delivery ledger + BullMQ max-effects (concurrency4) + Redis governor. No queue migration or new infrastructure. Runtime confirms PG guards survive duplicate queue jobs and the critical final-DB-commit-before-ACK crash. Ambiguous external submission stays UNKNOWN with no blind resend.\n\nInitial integration11/14 failed at raw Drizzle invite timestamps. Added failing IT-13 before minimal correction; raw expires_at string now becomes Date before getTime/toISOString. Added IT-14 concurrent/sequential semantic SELECT replay. Final integration16/16. A separate 17-scenario runtime harness exercises real isolated dependencies and exact crash barriers; all17 PASS. The first harness governor failure was its own abandoned waiter, corrected with request-ID reuse and measured interval assertions. No assertions or production limits weakened.\n\nActual checks:\n${checkText}\n\nFinal whitespace/secret/prohibited checks are recorded in artifacts/t103/COMMAND_RESULTS.json and SECRET_SCAN.json. Complete files: artifacts/t103/FILES_CHANGED.md. Exact source hashes, all failed/passing logs, Docker commands and outcomes are in artifacts/t103/. Literal resulting commit and clean state are recorded post-commit in ignored .run-evidence/t103-final-commit.json; resolve the tracked evidence commit using git log -1 --format=%H -- artifacts/t103/FINAL_VERIFICATION.json.\n\nContract deltas: none. Invite expiry serialization now honors its existing ISO contract. Queue, delivery ledger, governor, retry/concurrency, migrations, dependencies, MAX auth, provider and UI code unchanged.\n\nNOT_RUN: real MAX submission/delivery, provider rights/ingestion, actual MAX mobile/web, release deployment, disk loss/corruption, broad partition/load/soak testing. Risks: UNKNOWN may conservatively drop an unsent message; governor key loss needs explicit new epoch/10s warm hold/worker restart; safe retries terminate at5; stalled-job recovery observed62–93s; startup while PG is absent exits1 and needs restart/supervision; health/ready does not detect Redis-only outage. Running worker PG recovery and graceful active shutdown are proven.\n\nT107: no queue blocker from T103; other tickets/gates are not certified here. Next action: human review and integration owner decision; STOP.\n`);
fs.writeFileSync('docs/tasks/ACTIVE_TASK.md','# Active task — isolated T103 worktree\n\n**T103 PASS: KEEP_EXISTING_BULLMQ. Completed; stopped for human review.**\n\n- Explicit user activation applied only to `D:/Dev/Repos/The-Boys-Max-t103`, branch `codex/t103-bullmq-runtime`, baseline `5e4973f24fb74489387b3c29313cfcd1e8401ca7`.\n- [T103 handoff](../handoffs/T103_BULLMQ_RUNTIME.md), [verification](../../artifacts/t103/FINAL_VERIFICATION.json).\n- T101/T102 accepted baseline preserved. T104/T106 parallel worktrees and other tickets were not modified or accepted by this task.\n- No next implementation ticket active here. No push/merge; integration remains a human decision.\n');
const paths=[...new Set([...git('diff','--name-only','5e4973f24fb74489387b3c29313cfcd1e8401ca7').split('\n'),...git('ls-files','--others','--exclude-standard').split('\n'),`${base}/FILES_CHANGED.md`])].filter(Boolean).sort();
fs.writeFileSync(`${base}/FILES_CHANGED.md`,'# T103 changed files\n\nProduction: packages/persistence/plans.ts (raw timestamp conversion only). Tests: foundation IT-13/14 and isolated runtime/crash helpers. Docs: local task pointer/handoff and evidence. No queue/dependency/schema/UI/auth/provider code changes.\n\n'+paths.map(p=>'- '+p).join('\n')+'\n');
const scripts=fs.readdirSync(base).filter(p=>/\.(mjs|ps1)$/.test(p));fs.writeFileSync(`${base}/HARNESS_HASHES.json`,JSON.stringify(Object.fromEntries(scripts.map(p=>[`${base}/${p}`,createHash('sha256').update(fs.readFileSync(`${base}/${p}`)).digest('hex')])),null,2)+'\n');
console.log(JSON.stringify({status:'PASS',scenarios:scenarios.length,integration:'16/16',queue_decision:verification.queue_decision}));
